"""empty message

Revision ID: 18f4cfa1a7e7
Revises: cbbb49fd9622
Create Date: 2021-04-12 00:13:39.870899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f4cfa1a7e7'
down_revision = 'cbbb49fd9622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
