"""empty message

Revision ID: 2847c473cce5
Revises: 
Create Date: 2021-03-23 22:22:43.053798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2847c473cce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('currentTime', sa.DateTime(), nullable=False),
    sa.Column('predicted_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('trackingNumber', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('parish', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('gct', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_code', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.Column('cart', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('orderNumber'),
    sa.UniqueConstraint('trackingNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
