"""empty message

Revision ID: 4fb270a16491
Revises: 1ef94d09555c
Create Date: 2021-03-09 00:14:04.736662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb270a16491'
down_revision = '1ef94d09555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
