"""empty message

Revision ID: 50644d0f5a10
Revises: c8c8cd2e6853
Create Date: 2021-04-10 09:08:42.383545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50644d0f5a10'
down_revision = 'c8c8cd2e6853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesexpense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('exp_type', sa.String(), nullable=True),
    sa.Column('january', sa.Integer(), nullable=True),
    sa.Column('february', sa.Integer(), nullable=True),
    sa.Column('march', sa.Integer(), nullable=True),
    sa.Column('april', sa.Integer(), nullable=True),
    sa.Column('may', sa.Integer(), nullable=True),
    sa.Column('june', sa.Integer(), nullable=True),
    sa.Column('july', sa.Integer(), nullable=True),
    sa.Column('august', sa.Integer(), nullable=True),
    sa.Column('september', sa.Integer(), nullable=True),
    sa.Column('october', sa.Integer(), nullable=True),
    sa.Column('november', sa.Integer(), nullable=True),
    sa.Column('december', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salesexpense')
    # ### end Alembic commands ###
