"""empty message

Revision ID: 54d4cf48580c
Revises: 4d6456a56769
Create Date: 2021-04-11 20:12:06.572239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d4cf48580c'
down_revision = '4d6456a56769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fees', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fees', type_='unique')
    # ### end Alembic commands ###
