"""empty message

Revision ID: 7e4b6194ef4c
Revises: 583bfebbf754
Create Date: 2021-04-12 02:51:42.941869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4b6194ef4c'
down_revision = '583bfebbf754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fees', sa.Column('deliveryTime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fees', 'deliveryTime')
    # ### end Alembic commands ###
