"""empty message

Revision ID: e3dfa02153cf
Revises: bdee22c1deca
Create Date: 2021-03-03 02:41:41.495224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dfa02153cf'
down_revision = 'bdee22c1deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('stocklevel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'stocklevel')
    # ### end Alembic commands ###
